{% set name = "asaplib" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/asaplib-{{ version }}.tar.gz
  sha256: 05c48d435a5ddbec8e4e04518f27761e1a00943aaf111a5e53fcaf0e24e9fefd

build:
  entry_points:
    - asap = asaplib.cli.cmd_asap:asap
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - dscribe >=0.4.0
    - click >=7.0
    - numpy
    - scipy
    - scikit-learn
    - ase >=3.19.1
    - umap-learn
    - pyyaml
    - tqdm >=4.46.1
    - pandas

test:
  imports:
    - asaplib
  commands:
    - pip check
    - asap --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/BingqingCheng/ASAP
  summary: Automatic Selection And Prediction tools for materials and molecules
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
